name: klutter_ui
description: Flutter widgets to be used in conjunction with the klutter plugin.
version: 1.1.0
homepage: https://buijs.dev
repository: https://github.com/buijs-dev/klutter-dart-ui

environment:
  sdk: ">=2.17.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  coverage: ^1.6.4
  dartdoc: ^6.3.0
  pana: ^0.22.2
  test: ^1.24.7